### ISSUE TITLE
Hi there, Can you tell me how did you create loading screen of homepage. I am not able to create same behaviour on page

### ISSUE THREAD

**Issue by Enigma10** [eightants/reddium#3]
Can you tell me how did you create loading screen of homepage. I am not able to create same behaviour on page

**Comment by eightants** [comment]
Hey, many of the cards in Reddium have a loading state which will display if the contents are not defined. For example: https://github.com/eightants/reddium/blob/78aaccb6ae250883a2f4fee9f9a2fc1890ea833c/components/home-page/MidCard.tsx#L66-L83

Here, you can see that MidCard checks if `title` is defined on line 15, if it is not defined, it renders the highlighted HTML. The `shimmer-bg` class creates the loading 'pulse' animation.

**Comment by Enigma10** [comment]
@eightants hi, I have another doubt. Right now, the Next.js page is only rendering on the server-side and there is no loading coming back when the server is generating the `index.html` page. and I also want to know how sidebar `popular post` and `trending subreddit` is generating so fast without waiting for data.

I am really sorry for the stupid question but I am so confused right now and I am not able to figure what is wrong with my app.

**Comment by eightants** [comment]
No worries, my code might be a little confusing to those unfamiliar with Next.js

The Popular Post section, is just a dropdown selector, there is no data being fetched for that. It is an interaction for users to specify filter parameters for fetching posts. All the posts on Reddium are being fetched client-side, so that is how you see  the loading screen. 

The Trending Subreddit section is being rendered server-side. There is a subreddit where the top subreddits are posted every day, so I fetch this post and parse it to get the trending subreddits. Here is the code fetching trending subreddits: https://github.com/eightants/reddium/blob/78aaccb6ae250883a2f4fee9f9a2fc1890ea833c/pages/%5B%5B...params%5D%5D.tsx#L28-L32

Hope this helps!
